import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	inputWrapper: {
		marginHorizontal: 20,
		marginVertical: 10,
		padding: 20,
		gap: 5,
		borderRadius: 10,
		backgroundColor: '#46563a',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	inputContainer: {
		flexDirection: 'column',
		gap: 10,
		marginBottom: 10,
	},
	label: {
		fontFamily: 'Inter-Bold',
		color: 'white',
		fontSize: 12,
	},
	labelCenter: {
		fontFamily: 'Inter-Bold',
		color: 'white',
		textAlign: 'center',
		fontSize: 12,
	},
	button: {
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#f5f5f5',
		height: 35,

		borderRadius: 10,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	bottomButton: {
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#f5f5f5',
		padding: 10,
		width: '50%',
		borderRadius: 10,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	bottomButtonOutline: {
		alignItems: 'center',
		justifyContent: 'center',
		borderColor: '#f5f5f5',
		borderWidth: 1,
		padding: 10,
		width: '50%',
		borderRadius: 10,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	textButton: {
		color: '#46563a',
		fontSize: 13,
		fontFamily: 'Inter-Bold',
	},
	textButtonOutline: {
		color: 'white',
		fontSize: 13,
		fontFamily: 'Inter-Bold',
	},
	buttonContainer: {
		margin: 20,
		padding: 20,
		gap: 20,
		borderRadius: 10,
		backgroundColor: '#46563a',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	buttonWrapper: {
		flexDirection: 'row',
		width: '100%',
		gap: 20,
		justifyContent: 'space-evenly',
	},
	listContainer: {
		width: '100%',
		paddingHorizontal: 20,
	},
	touchableContainer: {
		flexDirection: 'row',
		padding: 10,
		marginVertical: 5,
		backgroundColor: 'white',
		justifyContent: 'space-between',
		borderRadius: 10,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	itemsAgregados: {
		fontSize: 15,
		fontFamily: 'Inter-Bold',
	},
	gasto: {
		fontSize: 15,
		textAlign: 'right',
		fontFamily: 'Inter-Regular',
	},
	textInput: {
		height: 35,
		paddingHorizontal: 10,
		fontSize: 14,
		width: '100%',
		backgroundColor: '#f5f5f5',
		borderRadius: 5,
		fontFamily: 'Inter-Regular',
	},
	settingsContainer: {
		width: '100%',
		marginBottom: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	settingsPrice: {
		gap: 10,
		width: '65%',
	},
	priceInput: {
		height: 35,
		paddingHorizontal: 10,
		fontSize: 14,
		width: '100%',
		backgroundColor: '#f5f5f5',
		borderRadius: 5,
		fontFamily: 'Inter-Regular',
	},
	settingsVegan: {
		gap: 10,
		alignItems: 'center',
		width: '35%',
	},
	centeredView: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 22,
	},
	totalPriceContainer: {
		flexDirection: 'row',
		width: '100%',
		gap: 10,
		alignItems: 'center',
		justifyContent: 'center',
		elevation: 2,
	},
	totalPrice: {
		fontSize: 14,
		textAlign: 'center',
		color: 'white',
		fontFamily: 'Inter-Bold',
	},
});
