import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		paddingVertical: 40,
		paddingHorizontal: 20,
		alignItems: 'center',
	},
	inputContainer: {
		width: '100%',
		padding: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	button: {
		width: '25%',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#88A61C',
		padding: 7,
		borderRadius: 10,
		elevation: 2,
	},
	textButton: {
		color: '#ecedf1',
		fontWeight: 'bold',
		fontSize: 15,
	},
	buttonContainer: {
		flexDirection: 'row',
		width: '100%',
		alignItems: 'center',
		justifyContent: 'space-around',
	},
	listContainer: {
		width: '90%',
		marginVertical: 10,
	},
	touchableContainer: {
		flexDirection: 'row',
		padding: 10,
		marginVertical: 5,
		backgroundColor: 'white',
		justifyContent: 'space-between',
		borderRadius: 10,
		elevation: 2,
	},
	itemsAgregados: {
		fontSize: 16,
		fontWeight: 'bold',
		width: '50%',
	},
	gasto: {
		fontSize: 16,
		width: '20%',
		textAlign: 'right',
	},
	vegan: {
		fontSize: 13,
		backgroundColor: '#88A61C',
		color: 'white',
		paddingVertical: 3,
		paddingHorizontal: 5,
	},
	noVegan: {
		fontSize: 13,
		backgroundColor: '#D60700',
		color: 'white',
		paddingVertical: 3,
		paddingHorizontal: 5,
	},
	textInput: {
		padding: 10,
		fontSize: 18,
		width: '70%',
		borderBottomColor: 'gainsboro',
		borderBottomWidth: 1,
	},
	settingsContainer: {
		width: '100%',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-evenly',
		borderBottomColor: '#88A61C',
		borderBottomWidth: 1,
		paddingBottom: 10,
	},
	settingsPrice: {
		width: '50%',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	priceInput: {
		fontSize: 16,
		borderBottomColor: 'gainsboro',
		borderBottomWidth: 1,
		padding: 5,
		textAlign: 'center',
	},
	settingsVegan: {
		width: '50%',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	centeredView: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 22,
	},
	totalPrice: {
		fontSize: 16,
		width: '60%',
		textAlign: 'center',
		fontWeight: "bold",
		marginVertical: 20,
		paddingVertical: 5,
		borderBottomColor: 'gainsboro',
		borderBottomWidth: 1,
	},
});
