import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		paddingVertical: 40,
		paddingHorizontal: 20,
		alignItems: 'center',
	},
	personContainer: {
		width: '100%',
		padding: 20,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	carnacasContainer: {
		width: '45%',
		alignContent: 'center',
		backgroundColor: 'white',
		elevation: 3,
		padding: 10,
		borderRadius: 10,
	},
	veganContainer: {
		width: '45%',
		alignContent: 'center',
		backgroundColor: 'white',
		elevation: 3,
		padding: 10,
		borderRadius: 10,
	},
	counter: {
		textAlign: 'center',
		fontSize: 25,
		paddingVertical: 10,
		fontWeight: 'bold',
	},
	totalPrice: {
		fontSize: 18,
		marginBottom: 10,
		textAlign: 'center',
		fontWeight: 'bold',
		paddingVertical: 5,
		borderBottomColor: 'gainsboro',
		borderBottomWidth: 1,
	},
	cuantos: {
		fontSize: 18,
		textAlign: 'center',
		width: '100%',
		borderBottomColor: '#88A61C',
		borderBottomWidth: 1,
		paddingBottom: 15,
	},
	boxTitle: {
		fontSize: 18,
		textAlign: 'center',
	},
	buttonContainer: {
		flexDirection: 'row',
		width: '100%',
		justifyContent: 'space-between',
	},
	increment: {
		backgroundColor: '#88A61C',
		width: '45%',
		alignItems: 'center',
		padding: 5,
		borderRadius: 5,
		elevation: 2,
		height: 35,
	},
	decrement: {
		backgroundColor: '#D60700',
		width: '45%',
		alignItems: 'center',
		padding: 5,
		borderRadius: 5,
		elevation: 2,
		height: 35,
	},
	buttonText: {
		color: '#ecedf1',
		fontSize: 16,
		fontWeight: 'bold',
	},
	buttonBottomContainer: {
		flexDirection: 'row',
		width: '100%',
		alignItems: 'center',
		justifyContent: 'space-around',
		bottom: 0,
		height: '20%',
		position: 'absolute',
	},
	cuantoPagan: {
		textAlign: 'center',
		fontSize: 18,
		fontWeight: 'bold',
	},
	resultContainer: {
		marginVertical: 10,
	},
});
