import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		paddingVertical: 20,
		paddingHorizontal: 20,
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	dataContainer: {
		width: '100%',
		alignItems: 'center',
		borderBottomColor: '#46563a',
		borderBottomWidth: 1,
	},
	personContainer: {
		width: '100%',
		flex: 1,
		padding: 10,
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	carnacasContainer: {
		width: '47%',
		height: '60%',
		alignContent: 'center',
		backgroundColor: 'white',
		elevation: 3,
		padding: 10,
		borderRadius: 10,
		justifyContent: 'space-between',
	},
	veganContainer: {
		width: '47%',
		height: '60%',
		alignContent: 'center',
		backgroundColor: 'white',
		elevation: 3,
		padding: 10,
		borderRadius: 10,
		justifyContent: 'space-between',
	},
	counter: {
		textAlign: 'center',
		fontSize: 35,
		fontFamily: 'Inter_700Bold',
	},
	totalPriceContainer: {
		marginVertical: 20,
		padding: 10,
		borderRadius: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'gainsboro',
		elevation: 2,
	},
	totalPrice: {
		fontSize: 15,
		textAlign: 'center',
		fontFamily: 'Inter_700Bold',
	},
	cuantos: {
		fontSize: 18,
		textAlign: 'center',
		width: '100%',
		paddingBottom: 15,
		fontFamily: 'Inter_400Regular',
	},
	boxTitle: {
		fontSize: 18,
		textAlign: 'center',
		backgroundColor: '#f5f5f5',
		padding: 5,
		borderRadius: 5,
		elevation: 3,
		fontFamily: 'Inter_400Regular',
	},
	buttonContainer: {
		flexDirection: 'row',
		width: '100%',
		justifyContent: 'space-between',
	},
	increment: {
		backgroundColor: '#46563a',
		width: '45%',
		alignItems: 'center',
		padding: 5,
		borderRadius: 5,
		elevation: 2,
		height: 35,
	},
	decrement: {
		backgroundColor: '#8C0700',
		width: '45%',
		alignItems: 'center',
		padding: 5,
		borderRadius: 5,
		elevation: 2,
		height: 35,
	},
	buttonText: {
		color: 'gainsboro',
		fontSize: 16,
		fontFamily: 'Inter_700Bold',
	},
	buttonContainer: {
		flexDirection: 'row',
		width: '100%',
		alignItems: 'center',
		justifyContent: 'space-around',
	},
	cuantoPagan: {
		textAlign: 'center',
		fontSize: 18,
		fontFamily: 'Inter_400Regular',
	},
	cuantoPrecio: {
		textAlign: 'center',
		fontSize: 18,
		fontFamily: 'Inter_700Bold',
	},
	resultContainer: {
		marginVertical: 10,
	},
});
